from pathlib import Path

import pandas as pd

from aridaq.validation import validate_columns, validate_values


NUMERIC_COLUMNS = [
    "cost_price",
    "selling_price",
    "current_stock",
    "units_sold",
    "days_observed",
    "lead_time_days",
    "min_stock",
    "max_stock",
]


def load_store_data(file_path: str | Path) -> pd.DataFrame:
    """
    Load a store CSV and prepare it for Aridaq Commerce.

    The function:
    1. Reads the CSV.
    2. Normalizes column names.
    3. Checks required columns.
    4. Converts numerical fields.
    5. Rejects invalid values.
    6. Adds calculated business metrics.
    """

    file_path = Path(file_path)

    if not file_path.exists():
        raise FileNotFoundError(
            f"Store data file not found: {file_path}"
        )

    if file_path.suffix.lower() != ".csv":
        raise ValueError("Aridaq Commerce currently requires a CSV file.")

    df = pd.read_csv(file_path)

    if df.empty:
        raise ValueError("The uploaded store dataset is empty.")

    # Normalize column names.
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )

    validate_columns(df.columns)

    # Convert required numerical fields.
    for column in NUMERIC_COLUMNS:
        df[column] = pd.to_numeric(
            df[column],
            errors="coerce"
        )

    if df[NUMERIC_COLUMNS].isnull().any().any():
        invalid_columns = (
            df[NUMERIC_COLUMNS]
            .columns[df[NUMERIC_COLUMNS].isnull().any()]
            .tolist()
        )

        raise ValueError(
            "Invalid numerical values found in: "
            + ", ".join(invalid_columns)
        )

    # Validate business rules.
    validate_values(
        df.to_dict(orient="records")
    )

    # Calculate core commerce metrics.

    df["unit_margin"] = (
        df["selling_price"] -
        df["cost_price"]
    )

    df["margin_rate"] = (
        df["unit_margin"] /
        df["selling_price"]
    )

    df["daily_sales_rate"] = (
        df["units_sold"] /
        df["days_observed"]
    )

    df["lead_time_demand"] = (
        df["daily_sales_rate"] *
        df["lead_time_days"]
    )

    df["inventory_after_lead_time"] = (
        df["current_stock"] -
        df["lead_time_demand"]
    )

    # Approximate days of inventory remaining.
    df["days_of_inventory"] = (
        df["current_stock"] /
        df["daily_sales_rate"].replace(0, float("nan"))
    )

    # Replace infinite values generated by zero sales.
    df["days_of_inventory"] = (
        df["days_of_inventory"]
        .replace([float("inf"), -float("inf")], float("nan"))
        .fillna(0)
    )

    return df